main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path('admin/', admin.site.urls), path('', include('tasks.urls'))]

# lambda

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.task_list, name='task-list'),
    path('task/<str:slug>', views.task_detail, name='task-detail'),
    path('task/<str:slug>/toggle/', views.task_toggle, name='task-toggle'),
    path('task/<str:slug>/edit/', views.task_edit, name='task-edit'),
    path('task/<str:slug>/delete/', views.task_delete, name='task-delete'),
    path('add/', views.add_task, name='add-task'),
    path('done/', views.show_done, name='show-done'),
    path('pending/', views.show_pending, name='show-pending'),
]

tasks/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200, blank=True, default=' ')
    slug = models.SlugField(max_length=100)
    done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    comple_before = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True, auto_now=True)

    def __str__(self):
        return self.name

tasks/forms.py
from django.forms import ModelForm

from .models import Task


class AddTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'comple_before')


class EditTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'done', 'comple_before')

tasks/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.utils.text import slugify

from .forms import AddTaskForm, EditTaskForm
from .models import Task


# Create your views here.
def task_list(request: HttpRequest) -> HttpResponse:
    num_tasks = Task.objects.count()
    tasks = Task.objects.all()
    num_d = tasks.filter(done=True).count()
    num_f = tasks.filter(done=False).count()
    return render(
        request,
        'tasks/list.html',
        {'num_tasks': num_tasks, 'tasks': tasks, 'num_d': num_d, 'num_f': num_f},
    )


def task_detail(request: HttpRequest, slug: str) -> HttpResponse:
    task = Task.objects.get(slug=slug)
    return render(request, 'tasks/detail.html', dict(task=task))


def add_task(request):
    if request.method == 'POST':
        if (form := AddTaskForm(request.POST)).is_valid():
            task = form.save(commit=False)
            task.slug = slugify(task.name)
            task.save()
            return redirect('tasks:add-task')
    else:
        form = AddTaskForm()
    return render(request, 'tasks/add_task.html', dict(form=form))


def task_toggle(request, slug: str):
    num_tasks = Task.objects.count()
    tasks = Task.objects.all()

    task = Task.objects.get(slug=slug)
    if task.done:
        task.done = False
        task.save()
    else:
        task.done = True
        task.save()
    num_d = tasks.filter(done=True).count()
    num_f = tasks.filter(done=False).count()
    return render(
        request,
        'tasks/list.html',
        {'num_tasks': num_tasks, 'tasks': tasks, 'num_d': num_d, 'num_f': num_f},
    )


def task_edit(request, slug: str):
    task = Task.objects.get(slug=slug)
    if request.method == 'POST':
        if (form := EditTaskForm(request.POST, instance=task)).is_valid():
            task = form.save(commit=False)
            task.slug = slugify(task.name)
            task.save()
            return redirect('tasks:task-list')
    else:
        form = EditTaskForm(instance=task)
    return render(request, 'tasks/edit.html', dict(task=task, form=form))


def task_delete(request, slug: str):
    Task.objects.filter(slug=slug).delete()
    num_tasks = Task.objects.count()
    tasks = Task.objects.all()
    num_d = tasks.filter(done=True).count()
    num_f = tasks.filter(done=False).count()
    return render(
        request,
        'tasks/list.html',
        {'num_tasks': num_tasks, 'tasks': tasks, 'num_d': num_d, 'num_f': num_f},
    )


def show_done(request: HttpRequest) -> HttpResponse:
    num_tasks = Task.objects.count()
    tasks = Task.objects.all()
    tasks_d = tasks.filter(done=True)
    num_d = tasks.filter(done=True).count()
    num_f = tasks.filter(done=False).count()
    return render(
        request,
        'tasks/list.html',
        {'num_tasks': num_tasks, 'tasks': tasks_d, 'num_d': num_d, 'num_f': num_f},
    )


def show_pending(request: HttpRequest) -> HttpResponse:
    num_tasks = Task.objects.count()
    tasks = Task.objects.all()
    tasks_f = tasks.filter(done=False)
    num_d = tasks.filter(done=True).count()
    num_f = tasks.filter(done=False).count()
    return render(
        request,
        'tasks/list.html',
        {'num_tasks': num_tasks, 'tasks': tasks_f, 'num_d': num_d, 'num_f': num_f},
    )

tasks/templates/tasks/add_task.html
{% extends "./base.html" %}
{% block title %}Task | Creation{% endblock title %}
{% block body %}

  <form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Crear">
  </form>

  <a href="{% url 'tasks:task-list' %}">Volver</a> 
{% endblock body %}

tasks/templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %} Tasks {% endblock title %}
  {% comment %} <link rel="stylesheet" href="{% static "style/custom.css" %}"> {% endcomment %}
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  {% block body %}{% endblock body %}
</body>
</html>

tasks/templates/tasks/detail.html
{% extends "./base.html" %}
{% block title %}Task | {{task.name}}{% endblock title %}
{% block body %}
<table>
  <h1>{{task.title}}</h1>
  <p>Creation Date: {{task.created_at}}</p>
  <p>Status: {%if task.done%}
    Task Done
  {% else %}   
    In Progres...
  {% endif %}</p>
  <h3>Definition:</h3>
  <p>{{task.description}}</p>

  <a href="{%url 'tasks:task-list'%}">Volver</a>
</table>
{% endblock body %}

tasks/templates/tasks/edit.html
{% extends "./base.html" %}
{% block title %}Task | Edit | {{task.name}}{% endblock title %}
{% block body %}
  <form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Guardar Edicion">
  </form>

  <a href="{% url 'tasks:task-list' %}">Volver</a> 
{% endblock body %}

tasks/templates/tasks/list.html
{% extends "./base.html" %}
{% block title %}Tasks | Home{% endblock title %}
{% block body %}
  <p class="h1">Welcome to the taks manager</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><a href="{% url "tasks:task-list" %}">Total tasks</a></th>
        <th><a href="{% url "tasks:show-done" %}">Total ✅</a></th>
        <th><a href="{% url "tasks:show-pending" %}">Total ❌</a></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <strong>{{num_tasks}}</strong> task{{num_tasks | pluralize}}</td>
        <td><strong>{{num_d}}</strong> task{{num_d | pluralize}}</td>
        <td><strong>{{num_f}}</strong> task{{num_f | pluralize}}</td>
      </tr>
    </tbody>
  </table>
  <a href="{% url 'tasks:add-task'%}">Crear Tarea</a> 
  <div class="row">
    {%for task in tasks%}
    <div class="container col-sm bg-primary mt-4 p-3 rounded">
        <a href="{% url 'tasks:task-detail' task.slug %}">{{task}} : {%if task.done%}
          ✅
        {% else %}   
          ❌
        {% endif %}</a> 
       <br>
          {%if task.done%}
            <a href="{% url 'tasks:task-toggle' task.slug %}"><button class="btn btn-secondary">Unfinish</button></a>
          {% else %}   
          <a href="{% url 'tasks:task-toggle' task.slug %}"><button class="btn btn-success">Complete</button></a>
          {% endif %}
        <a href="{% url 'tasks:task-edit' task.slug %}"><button class="btn btn-info">Edit</button></a>
        <a href="{% url 'tasks:task-delete' task.slug %}"><button class="btn btn-danger">Delete</button></a>
    </div>
    
    {% endfor %}
  </div>
{% endblock body %}